apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-kubecon
spec:
  containers:
  - name: memory-demo-kubecon
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "50Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "750M", "--vm-hang", "1"]
