apiVersion: v1
kind: Pod
metadata:
  name: redis
  annotations:
    co.elastic.hints/package: redis
    co.elastic.hints/data_streams: info, log
    co.elastic.hints/host: '${kubernetes.pod.ip}:6379'
    co.elastic.hints/info.period: 10s
  labels:
    k8s-app: redis
    app: redis
spec:
  initContainers:
  - name: init-container42
    image: busybox
    command: ["echo","I am init-conatiner"]
  containers:
  - image: redis
    imagePullPolicy: IfNotPresent
    name: redis42
    ports:
    - name: redis
      containerPort: 6379
      protocol: TCP
